import { fileURLToPath, URL } from "node:url";
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: [
      "packages/kernel/src/__tests__/**/*.test.ts",
      "packages/plugin-api/src/__tests__/**/*.test.ts",
      "apps/bridge/src/kernel/__tests__/**/*.test.ts",
      "apps/bridge/src/plugins/__tests__/route-hot-reload.test.ts",
      "apps/bridge/src/plugins/__tests__/plugin-runtime-isolation.test.ts",
      "apps/bridge/src/plugins/__tests__/plugin-child-sandbox.test.ts",
      "apps/bridge/src/services/__tests__/plugin-pipeline.test.ts",
      "apps/bridge/src/services/__tests__/marketplace-acquisition.test.ts",
      "apps/bridge/src/services/__tests__/marketplace-commerce.test.ts",
      "apps/bridge/src/services/__tests__/marketplace-listing-policy.test.ts",
      "apps/bridge/src/services/__tests__/marketplace-plugin-pin.test.ts",
      "apps/bridge/src/services/__tests__/marketplace-official-catalog-pins.test.ts",
      "apps/bridge/src/services/__tests__/marketplace-catalog-tenant.test.ts",
      "apps/bridge/src/services/__tests__/marketplace-catalog-fetch.test.ts",
      "apps/bridge/src/services/__tests__/marketplace-catalog-claim.test.ts",
      "apps/bridge/src/services/__tests__/marketplace-catalog-bundle.test.ts",
      "apps/bridge/src/services/__tests__/marketplace-community-shelf.test.ts",
      "apps/bridge/src/services/__tests__/marketplace-guest-checkout.test.ts",
      "apps/bridge/src/services/__tests__/marketplace-listing-indexes.test.ts",
      "apps/bridge/src/services/__tests__/marketplace-verified-publisher.test.ts",
      "apps/bridge/src/services/__tests__/marketplace-verified-seller.test.ts",
      "apps/bridge/src/services/__tests__/marketplace-stripe-connect.test.ts",
      "apps/bridge/src/services/__tests__/plugin-capabilities.test.ts",
      "apps/bridge/src/routes/__tests__/marketplace-listings-query.test.ts",
      "apps/bridge/src/services/__tests__/release-flow.test.ts",
      "apps/bridge/src/services/__tests__/github-projects-status-map.test.ts",
      "apps/bridge/src/services/__tests__/github-projects-context.test.ts",
      "apps/bridge/src/services/__tests__/github-projects-comments.test.ts",
      "apps/bridge/src/services/__tests__/github-projects-timeline.test.ts",
      "apps/bridge/src/services/__tests__/github-projects-fields.test.ts",
      "apps/bridge/src/services/__tests__/board-columns-crud.test.ts",
      "apps/bridge/src/services/__tests__/github-app-webhook-sig.test.ts",
      "apps/bridge/src/services/__tests__/github-integration-authorize-url.test.ts",
      "apps/bridge/src/services/__tests__/github-pr-ci.test.ts",
      "apps/bridge/src/services/__tests__/github-repo-create.test.ts",
      "apps/bridge/src/services/__tests__/pick-github-installation.test.ts",
      "apps/bridge/src/services/__tests__/multi-board-tasks-migration.test.ts",
      "apps/bridge/src/services/__tests__/prompt-assembler-order.test.ts",
      "apps/bridge/src/services/__tests__/cursor-cloud-transcript.test.ts",
      "apps/bridge/src/services/__tests__/cursor-cloud-setting-sources.test.ts",
      "apps/bridge/src/services/__tests__/cursor-sandbox-policy.test.ts",
      "apps/bridge/src/services/__tests__/cursor-cloud-sdk-options.test.ts",
      "apps/bridge/src/services/__tests__/cursor-cloud-resume.test.ts",
      "apps/bridge/src/services/__tests__/chat-turn-state.test.ts",
      "apps/bridge/src/services/__tests__/cursor-subscription-cache.test.ts",
      "apps/bridge/src/services/__tests__/git-workspace.test.ts",
      "apps/bridge/src/services/__tests__/git-tools.test.ts",
      "apps/bridge/src/services/__tests__/git-net-mode.test.ts",
      "apps/bridge/src/services/__tests__/git-host-connector.test.ts",
      "apps/bridge/src/services/__tests__/intelligence-toolallow-repair.test.ts",
      "apps/bridge/src/services/__tests__/confirm-policy-git.test.ts",
      "apps/bridge/src/services/__tests__/github-release.test.ts",
      "apps/bridge/src/services/__tests__/release-submissions.test.ts",
      "apps/bridge/src/services/__tests__/publisher-connectors.test.ts",
      "apps/bridge/src/services/__tests__/support-to-kanban.test.ts",
      "apps/bridge/src/services/__tests__/coding-hooks.test.ts",
      "apps/bridge/src/services/__tests__/explore-coding.test.ts",
      "apps/bridge/src/services/__tests__/run-card-title.test.ts",
      "apps/bridge/src/services/__tests__/active-work-run-card.test.ts",
      "apps/bridge/src/services/__tests__/fs-tools-preview.test.ts",
      "apps/bridge/src/services/__tests__/fs-tools-workspace.test.ts",
      "apps/bridge/src/services/__tests__/coding-tenant-isolation.test.ts",
      "apps/bridge/src/services/__tests__/coding-workspace-seed.test.ts",
      "apps/bridge/src/services/__tests__/terminal-sandbox.test.ts",
      "apps/bridge/src/services/__tests__/terminal-egress-proxy.test.ts",
      "apps/bridge/src/services/__tests__/sandboxed-process.test.ts",
      "apps/bridge/src/services/__tests__/tenant-worktree.test.ts",
      "apps/bridge/src/services/__tests__/coding-ui-access.test.ts",
      "apps/bridge/src/services/__tests__/coding-quota.test.ts",
      "apps/bridge/src/services/__tests__/spend-authority.test.ts",
      "apps/bridge/src/services/__tests__/deploy-authority.test.ts",
      "apps/bridge/src/services/__tests__/delete-authority.test.ts",
      "apps/bridge/src/services/__tests__/send-authority.test.ts",
      "apps/bridge/src/services/__tests__/authority-audit-admin.test.ts",
      "apps/bridge/src/services/__tests__/agent-pause-authority.test.ts",
      "apps/bridge/src/services/__tests__/coding-terminal-route.test.ts",
      "apps/bridge/src/services/__tests__/chat-ws-protocol.test.ts",
      "apps/bridge/src/services/__tests__/terminal-session-manager.test.ts",
      "apps/bridge/src/services/__tests__/ws-upgrade-router.test.ts",
      "apps/bridge/src/services/__tests__/ephemeral-build.test.ts",
      "apps/bridge/src/services/__tests__/exa-web.test.ts",
      "apps/bridge/src/services/__tests__/vault-agent-scope.test.ts",
      "apps/bridge/src/services/__tests__/user-vault-scope.test.ts",
      "apps/bridge/src/services/__tests__/github-connect-user-vault.test.ts",
      "apps/bridge/src/services/__tests__/wiki-workspace-migrate.test.ts",
      "apps/bridge/src/services/__tests__/hooks-workspace-migrate.test.ts",
      "apps/bridge/src/services/__tests__/platform-events-workspace-migrate.test.ts",
      "apps/bridge/src/services/__tests__/host-users-hub.test.ts",
      "apps/bridge/src/services/__tests__/secret-scrub.test.ts",
      "apps/bridge/src/services/__tests__/build-supervisor-lib.test.ts",
      "apps/bridge/src/services/__tests__/build-supervisor-egress-network.test.ts",
      "apps/bridge/src/services/__tests__/write-tool-verify.test.ts",
      "apps/bridge/src/services/__tests__/cursor-workspace-knowledge.test.ts",
      "apps/bridge/src/services/__tests__/cursor-mcp-config.test.ts",
      "apps/bridge/src/services/__tests__/mcp-workspace-store.test.ts",
      "apps/bridge/src/services/__tests__/mcp-host.test.ts",
      "apps/bridge/src/services/__tests__/cursor-cloud-mcp.test.ts",
      "apps/bridge/src/services/__tests__/compaction-scratchpad.test.ts",
      "apps/bridge/src/services/__tests__/code-index.test.ts",
      "apps/bridge/src/services/embeddings/__tests__/profiles.test.ts",
      "apps/bridge/src/services/embeddings/__tests__/embed-queue.test.ts",
      "apps/bridge/src/services/embeddings/__tests__/vector-retrieval.test.ts",
      "apps/bridge/src/services/__tests__/timeseries-store.test.ts",
      "apps/bridge/src/services/__tests__/platform-backup-archive.test.ts",
      "apps/bridge/src/services/__tests__/tenant-database-export.test.ts",
      "apps/bridge/src/services/__tests__/delegation-timeout.test.ts",
      "apps/bridge/src/services/__tests__/saas-entitlements.test.ts",
      "apps/bridge/src/services/__tests__/saas-subscriptions.test.ts",
      "apps/bridge/src/services/__tests__/admin-users-provision.test.ts",
      "apps/bridge/src/services/auth/__tests__/mfa-and-tokens.test.ts",
      "apps/bridge/src/services/auth/__tests__/mailer-key.test.ts",
      "apps/bridge/src/services/auth/__tests__/auth-security.http.test.ts",
      "apps/bridge/src/services/__tests__/feature-docs-images.test.ts",
      "apps/web/src/__tests__/**/*.test.ts",
      "apps/web/src/__tests__/**/*.test.tsx",
      "apps/web/src/pages/records/__tests__/**/*.test.tsx",
    ],
    environment: "node",
    globals: false,
    // Several suites exercise the singleton core database and its migrations.
    // Serial files prevent independent workers from racing the same schema.
    fileParallelism: false,
    restoreMocks: true,
  },
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./apps/web/src", import.meta.url)),
    },
  },
});
