import type { BuiltinSpec } from "./shared.js";
import { PLATFORM_ACTION_METADATA } from "../adapters/platform-actions.js";

export const COLLABORATION_SPECS: BuiltinSpec[] = [
  { name: "DirectConversation", label: "Direct Conversation", module: "messages", id: "dm_conversation_read", table: "dm_conversations", database: "core", defaultSort: "updated_at", accessPolicy: "relationship-scoped", writable: ["kind", "title", "member_user_ids"], operations: ["list", "get", "create"], actions: PLATFORM_ACTION_METADATA.DirectConversation, fields: ["id", "kind", "title", ["member_user_ids", "JSON"], "created_by_user_id", "created_at", "updated_at", "last_message_at", "last_message_preview"] },
  { name: "DirectMessage", label: "Direct Message", module: "messages", id: "dm_message_read", table: "dm_messages", database: "core", defaultSort: "created_at", accessPolicy: "relationship-scoped", writable: ["conversation_id", "body_text", "attachments"], required: ["conversation_id"], operations: ["list", "get", "create"], actions: PLATFORM_ACTION_METADATA.DirectMessage, fields: ["id", "conversation_id", "sender_user_id", "body_text", ["attachments", "JSON"], "created_at", "edited_at", "deleted_at"] },
  { name: "DmBlob", label: "DM Blob", module: "messages", id: "dm_blob_service", table: "dm_blobs", database: "core", defaultSort: "created_at", accessPolicy: "relationship-scoped", operations: ["list", "get"], actions: PLATFORM_ACTION_METADATA.DmBlob, fields: ["id", "owner_user_id", "filename", "mime", ["size", "Int"], "created_at"] },
  { name: "FederatedShareInvite", label: "Federated Share Invite", module: "messages", id: "federated_share_invite_service", table: "federated_share_invites", database: "core", accessPolicy: "relationship-scoped", operations: [], actions: PLATFORM_ACTION_METADATA.FederatedShareInvite, fields: ["id", "owner_tenant_id", "owner_user_id", "resource_kind", "resource_id", "role", "invitee_email", "status", "expires_at", "accepted_peer_connection_id", "created_at"] },
  { name: "PlatformGroup", label: "Platform Group", module: "messages", id: "platform_group_service", table: "platform_groups", database: "core", accessPolicy: "relationship-scoped", fields: ["id", "slug", "name", "description", "created_at"] },
  { name: "PlatformGroupMember", label: "Platform Group Member", module: "messages", id: "platform_group_member_service", table: "platform_group_members", database: "core", accessPolicy: "relationship-scoped", actions: PLATFORM_ACTION_METADATA.PlatformGroupMember, fields: ["id", "group_id", "member_kind", "member_id", "tenant_id", "created_at"] },
];
