import type { BuiltinSpec } from "./shared.js";
import { PLATFORM_ACTION_METADATA } from "../adapters/platform-actions.js";

export const CONNECTIVITY_SUPPORT_SPECS: BuiltinSpec[] = [
  { name: "BridgeConnection", label: "Bridge Connection", module: "platform", id: "bridge_connection_read", table: "bridge_connections", database: "core", scope: "tenant", scopeColumn: "owner_tenant_id", defaultSort: "updated_at", writable: ["label", "mode", "remote_bridge_url"], required: ["label", "mode"], operations: ["list", "get", "create", "delete"], actions: PLATFORM_ACTION_METADATA.BridgeConnection, fields: ["id", "owner_tenant_id", "owner_user_id", "label", "mode", "remote_bridge_url", "status", "last_seen_at", "created_at", "updated_at"] },
  { name: "PeerConnection", label: "Peer Connection", module: "platform", id: "peer_connection_read", table: "peer_connections", database: "core", scope: "user", scopeColumn: "local_user_id", defaultSort: "updated_at", actions: PLATFORM_ACTION_METADATA.PeerConnection, fields: ["id", "local_user_id", "remote_bridge_url", "remote_user_id", "remote_display_name", "remote_email", "status", "last_health_at", "created_at", "updated_at"] },
  { name: "SupportTicket", label: "Support Ticket", module: "support", id: "support_ticket_read", table: "support_tickets", database: "core", scope: "tenant", scopeColumn: "requester_tenant_id", defaultSort: "updated_at", accessPolicy: "relationship-scoped", writable: ["subject", "body", "category", "priority", "target_kind", "shared_grant_id", "owner_user_id"], required: ["subject"], operations: ["list", "get", "create"], actions: PLATFORM_ACTION_METADATA.SupportTicket, fields: ["id", "requester_kind", "requester_id", "requester_tenant_id", "subject", "body", "category", "status", "priority", "target_kind", "shared_grant_id", "owner_user_id", "created_at", "updated_at"] },
  { name: "SupportMessage", label: "Support Message", module: "support", id: "support_message_read", table: "support_messages", database: "core", defaultSort: "created_at", accessPolicy: "relationship-scoped", actions: PLATFORM_ACTION_METADATA.SupportMessage, fields: ["id", "ticket_id", "author_kind", "author_id", "body", "created_at"] },
];
