import type { BuiltinSpec } from "./shared.js";
import type { ActionDef } from "@godmode/kernel";
import { CONTENT_LIFECYCLE_ACTIONS } from "../adapters/content.js";
import { PLATFORM_ACTION_METADATA } from "../adapters/platform-actions.js";

const AGENT_ACTIONS: ActionDef[] = [
  { name: "clone", label: "Clone", target: "record", effect: "write", execution: "sync", roles: ["owner", "intelligence"], idempotency: { required: true }, inputSchema: { type: "object", required: ["name"], properties: { id: { type: "string" }, name: { type: "string" }, description: { type: "string" }, parent_id: { type: ["string", "null"] }, team: { type: ["string", "null"] } }, additionalProperties: false } },
  { name: "assign", label: "Assign", target: "record", effect: "write", execution: "sync", roles: ["owner", "intelligence"], confirmation: { required: true }, inputSchema: { type: "object", required: ["scope_type", "scope_id"], properties: { scope_type: { enum: ["department", "division", "page"] }, scope_id: { type: "string" }, role: { enum: ["viewer", "editor", "owner"] } }, additionalProperties: false } },
  { name: "configure_reflection", label: "Configure Reflection", target: "record", effect: "write", execution: "sync", roles: ["owner", "intelligence"], confirmation: { required: true }, inputSchema: { type: "object", properties: { enabled: { type: "boolean" }, mode: { enum: ["approval", "auto"] }, schedule: { type: "object" }, idle: { type: "object" } }, additionalProperties: false } },
  { name: "run_reflection", label: "Run Reflection", target: "record", effect: "external", execution: "sync", roles: ["owner", "intelligence"], confirmation: { required: true }, idempotency: { required: true }, inputSchema: { type: "object", additionalProperties: false } },
];

export const INTELLIGENCE_SPECS: BuiltinSpec[] = [
  { name: "Artifact", label: "Artifact", module: "intelligence", id: "artifact_service", table: "ai_artifacts", defaultSort: "updated_at", writable: ["name", "content", "kind", "mime_type", "description", "source"], required: ["name"], operations: ["list", "get", "create", "update", "delete"], fields: ["id", "agent_id", "name", "content", "kind", "mime_type", ["size_bytes", "Int"], "description", "source", ["has_content", "Check"], "created_at", "updated_at"] },
  { name: "Rule", label: "Rule", module: "intelligence", id: "rule_service", table: "ai_rules", defaultSort: "updated_at", writable: ["id", "description", "body", "always_apply", "globs_json", "departments_json", "priority", "enabled", "status"], required: ["description", "body"], operations: ["list", "get", "create", "update", "delete"], actions: CONTENT_LIFECYCLE_ACTIONS, fields: ["id", "agent_id", "description", "body", ["always_apply", "Check"], ["globs_json", "JSON"], ["departments_json", "JSON"], ["priority", "Int"], ["enabled", "Check"], "status", ["version", "Int"], "created_at", "updated_at"] },
  { name: "Skill", label: "Skill", module: "intelligence", id: "skill_service", table: "ai_skills", defaultSort: "updated_at", writable: ["name", "description", "body", "tools_json", "departments_json", "enabled", "status"], required: ["name", "body"], operations: ["list", "get", "create", "update", "delete"], actions: CONTENT_LIFECYCLE_ACTIONS, fields: ["id", "agent_id", "name", "description", "body", ["tools_json", "JSON"], ["departments_json", "JSON"], ["enabled", "Check"], "status", ["version", "Int"], "created_at", "updated_at"] },
  { name: "PromptTemplate", label: "Prompt Template", module: "intelligence", id: "prompt_read", table: "ai_prompts", defaultSort: "updated_at", fields: ["id", "agent_id", "kind", "label", "content", ["version", "Int"], "created_at", "updated_at"] },
  { name: "Memory", label: "Memory", module: "intelligence", id: "memory_service", table: "ai_memories", defaultSort: "updated_at", writable: ["id", "scope", "chat_id", "text", "category", "source", "enabled", "status", "pack_id", "valid_from", "valid_until"], required: ["text"], operations: ["list", "get", "create", "update", "delete"], actions: CONTENT_LIFECYCLE_ACTIONS, fields: ["id", "agent_id", "scope", "chat_id", "text", "category", "source", ["enabled", "Check"], "status", "pack_id", "valid_from", "valid_until", "created_at", "updated_at"] },
  { name: "ReflectionProposal", label: "Reflection Proposal", module: "intelligence", id: "reflection_proposal_service", table: "ai_reflection_proposals", defaultSort: "updated_at", writable: ["kind", "target_id", "action", "payload_json"], required: ["kind", "action"], operations: ["list", "get", "create"], actions: CONTENT_LIFECYCLE_ACTIONS, fields: ["id", "agent_id", "kind", "target_id", "action", ["payload_json", "JSON"], "status", "created_at", "updated_at"] },
  { name: "Agent", label: "Agent", module: "intelligence", id: "agent_service", table: "ai_agents", defaultSort: "updated_at", writable: ["id", "name", "description", "icon", "backend", "enabled", "parent_id", "team"], required: ["name"], operations: ["list", "get", "create", "update", "delete"], actions: AGENT_ACTIONS, fields: ["id", "name", "description", "icon", "backend", ["enabled", "Check"], ["is_template", "Check"], "parent_id", "team", "created_at", "updated_at"] },
  { name: "AgentAssignment", label: "Agent Assignment", module: "intelligence", id: "agent_assignment_service", table: "ai_agent_assignments", idColumn: "scope_id", writable: ["scope_type", "scope_id", "agent_id", "role"], required: ["scope_type", "scope_id", "agent_id"], operations: ["list", "get", "create", "update", "delete"], fields: ["id", "scope_type", "scope_id", "agent_id", "role", "updated_at"] },
  { name: "InferenceEndpoint", label: "Inference Endpoint", module: "intelligence", id: "inference_endpoint_read", table: "inference_endpoints", database: "core", scope: "tenant", scopeColumn: "owner_tenant_id", defaultSort: "created_at", writable: ["name", "base_model_path", "adapter_ids_json", "meter_unit", "meter_rate", "capacity_hint"], required: ["name", "base_model_path"], operations: ["list", "get", "create"], actions: PLATFORM_ACTION_METADATA.InferenceEndpoint, fields: ["id", "owner_tenant_id", "owner_user_id", "name", "base_model_path", ["adapter_ids_json", "JSON"], "meter_unit", ["meter_rate", "Int"], ["capacity_hint", "Int"], "status", "created_at"] },
];
