import type { BuiltinSpec } from "./shared.js";
import { PLATFORM_ACTION_METADATA } from "../adapters/platform-actions.js";

export const MARKETPLACE_SPECS: BuiltinSpec[] = [
  {
    name: "MarketplaceListing",
    label: "Marketplace Listing",
    module: "marketplace",
    id: "marketplace_listing_read",
    table: "marketplace_listings",
    database: "cloud",
    defaultSort: "updated_at",
    accessPolicy: "relationship-scoped",
    actions: PLATFORM_ACTION_METADATA.MarketplaceListing,
    fields: [
      "id",
      "seller_user_id",
      "seller_tenant_id",
      "kind",
      "resource_id",
      "title",
      "description",
      ["price_credits", "Int"],
      ["price_cents", "Int"],
      "currency",
      "seller_kind",
      "catalog_entry_id",
      "visibility",
      "status",
      "delivery_mode",
      "pricing_model",
      "price_period",
      "meter_unit",
      ["meter_rate", "Float"],
      "license",
      "inference_endpoint_id",
      "catalog_plugin_ref",
      "catalog_plugin_digest",
      "live_resource_id",
      "live_bundle_digest",
      "live_bound_at",
      "created_at",
      "updated_at",
    ],
  },
  {
    name: "MarketplaceEntitlement",
    label: "Marketplace Entitlement",
    module: "marketplace",
    id: "marketplace_entitlement_read",
    table: "marketplace_entitlements",
    database: "cloud",
    scope: "tenant",
    scopeColumn: "buyer_tenant_id",
    defaultSort: "updated_at",
    actions: PLATFORM_ACTION_METADATA.MarketplaceEntitlement,
    fields: [
      "id",
      "listing_id",
      "buyer_user_id",
      "buyer_tenant_id",
      "kind",
      "owner_tenant_id",
      "resource_kind",
      "resource_id",
      "status",
      "expires_at",
      "created_at",
      "updated_at",
    ],
  },
  {
    name: "MarketplaceOrder",
    label: "Marketplace Order",
    module: "marketplace",
    id: "marketplace_order_read",
    table: "marketplace_orders",
    database: "cloud",
    defaultSort: "created_at",
    accessPolicy: "relationship-scoped",
    actions: PLATFORM_ACTION_METADATA.MarketplaceOrder,
    fields: [
      "id",
      "listing_id",
      "catalog_entry_id",
      "buyer_user_id",
      "buyer_tenant_id",
      "seller_user_id",
      "seller_kind",
      ["amount_cents", "Int"],
      ["platform_fee_cents", "Int"],
      "currency",
      "provider",
      "provider_ref",
      "crypto_tx_hash",
      "status",
      "delivered_at",
      "created_at",
      "updated_at",
    ],
  },
  {
    name: "MarketplaceSellerAccount",
    label: "Marketplace Seller Account",
    module: "marketplace",
    id: "marketplace_seller_account_read",
    table: "marketplace_seller_accounts",
    database: "cloud",
    defaultSort: "updated_at",
    accessPolicy: "relationship-scoped",
    actions: PLATFORM_ACTION_METADATA.MarketplaceSellerAccount,
    fields: [
      "id",
      "user_id",
      "stripe_connect_account_id",
      "paypal_merchant_id",
      "metamask_address",
      "payout_preference",
      "onboarding_status",
      "tos_accepted_version",
      "tos_accepted_at",
      ["verified_seller", "Int"],
      ["verified_frozen", "Int"],
      "created_at",
      "updated_at",
    ],
  },
  {
    name: "CatalogSource",
    label: "Catalog Source",
    module: "marketplace",
    id: "catalog_source_read",
    table: "catalog_sources",
    database: "cloud",
    scope: "user",
    writable: ["name", "url"],
    required: ["name", "url"],
    operations: ["list", "get", "create", "delete"],
    actions: PLATFORM_ACTION_METADATA.CatalogSource,
    fields: ["id", "user_id", "name", "url", "created_at"],
  },
  {
    name: "CatalogInstall",
    label: "Catalog Install",
    module: "marketplace",
    id: "catalog_install_read",
    table: "catalog_installs",
    database: "cloud",
    scope: "tenant",
    defaultSort: "installed_at",
    actions: PLATFORM_ACTION_METADATA.CatalogInstall,
    fields: [
      "id",
      "tenant_id",
      "user_id",
      "entry_id",
      "entry_title",
      "install_type",
      "source_catalog",
      "installed_at",
    ],
  },
  {
    name: "MarketplaceCatalog",
    label: "Marketplace Catalog",
    module: "marketplace",
    id: "marketplace_catalog_service",
    table: "marketplace_catalog",
    database: "cloud",
    accessPolicy: "relationship-scoped",
    operations: [],
    actions: PLATFORM_ACTION_METADATA.MarketplaceCatalog,
    fields: ["id", "user_id", "created_at", "updated_at"],
  },
];
