import type { ActionDef } from "@godmode/kernel";
import type { BuiltinSpec } from "./shared.js";
import { NOTIFICATION_ACTIONS } from "../adapters/content.js";
import { PLATFORM_ACTION_METADATA } from "../adapters/platform-actions.js";
import { IDENTITY_ADMIN_ACTIONS } from "../adapters/identity-admin.js";
import { PLATFORM_CONFIG_ACTIONS } from "../adapters/platform-config.js";

const UPDATE_ADMIN_ROLES = ["owner", "intelligence"] as const;
const UPDATE_EMPTY_INPUT = { type: "object", additionalProperties: false };
const UPDATE_ACTIONS: ActionDef[] = [
  {
    name: "check_now",
    label: "Check Now",
    target: "record",
    effect: "external",
    execution: "async",
    roles: [...UPDATE_ADMIN_ROLES],
    inputSchema: UPDATE_EMPTY_INPUT,
    idempotency: { required: true, ttlSeconds: 60 },
    retry: { maxAttempts: 3, backoffMs: 1000 },
    timeoutMs: 30_000,
    cancellable: false,
  },
  {
    name: "download",
    label: "Download",
    target: "record",
    effect: "external",
    execution: "async",
    roles: [...UPDATE_ADMIN_ROLES],
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: { release_id: { type: "string" } },
    },
    confirmation: { required: true, ttlSeconds: 300 },
    idempotency: { required: true },
    retry: { maxAttempts: 3, backoffMs: 2_000 },
    timeoutMs: 300_000,
    cancellable: true,
  },
  ...["defer", "skip_release"].map((name) => ({
    name,
    label: name === "defer" ? "Defer" : "Skip Release",
    target: "record" as const,
    effect: "write" as const,
    execution: "sync" as const,
    roles: [...UPDATE_ADMIN_ROLES],
    inputSchema:
      name === "defer"
        ? {
            type: "object",
            additionalProperties: false,
            properties: { until: { type: "string" } },
          }
        : UPDATE_EMPTY_INPUT,
    confirmation: { required: true, ttlSeconds: 300 },
    idempotency: { required: true },
  })),
  {
    name: "configure",
    label: "Configure",
    target: "record",
    effect: "write",
    execution: "sync",
    roles: [...UPDATE_ADMIN_ROLES],
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        channel: { enum: ["stable", "nightly"] },
        auto_check: { type: "boolean" },
        manifest_url: { type: "string" },
        poll_min_ms: { type: "number" },
        poll_max_ms: { type: "number" },
      },
    },
    confirmation: { required: true, ttlSeconds: 300 },
    idempotency: { required: true },
  },
  {
    name: "preflight",
    label: "Preflight",
    target: "record",
    effect: "read",
    execution: "async",
    roles: [...UPDATE_ADMIN_ROLES],
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: { release_id: { type: "string" } },
    },
    idempotency: { required: true, ttlSeconds: 30 },
    timeoutMs: 120_000,
    cancellable: false,
  },
  {
    name: "create_snapshot",
    label: "Create Snapshot",
    target: "record",
    effect: "write",
    execution: "async",
    roles: [...UPDATE_ADMIN_ROLES],
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: { release_id: { type: "string" } },
    },
    confirmation: { required: true, ttlSeconds: 300 },
    idempotency: { required: true },
    timeoutMs: 900_000,
    cancellable: false,
  },
  ...["apply", "restart_to_apply"].map((name) => ({
    name,
    label: name === "apply" ? "Apply" : "Restart to Apply",
    target: "record" as const,
    effect: "external" as const,
    execution: "async" as const,
    roles: [...UPDATE_ADMIN_ROLES],
    inputSchema: UPDATE_EMPTY_INPUT,
    confirmation: { required: true, ttlSeconds: 120 },
    idempotency: { required: true },
    timeoutMs: 120_000,
    cancellable: false,
  })),
];

const RELEASE_ACTIONS: ActionDef[] = [
  {
    name: "preflight",
    label: "Preflight",
    target: "record",
    effect: "read",
    execution: "async",
    roles: [...UPDATE_ADMIN_ROLES],
    inputSchema: UPDATE_EMPTY_INPUT,
    idempotency: { required: true, ttlSeconds: 30 },
    timeoutMs: 120_000,
    cancellable: false,
  },
  {
    name: "compatibility",
    label: "Compatibility",
    target: "record",
    effect: "read",
    execution: "sync",
    roles: [...UPDATE_ADMIN_ROLES],
    inputSchema: UPDATE_EMPTY_INPUT,
  },
];

export const PLATFORM_SPECS: BuiltinSpec[] = [
  { name: "Notification", label: "Notification", module: "platform", id: "notification_service", table: "notifications", database: "core", scope: "tenant", scopeColumn: "recipient_tenant_id", defaultSort: "created_at", writable: ["recipient_kind", "recipient_id", "recipient_tenant_id", "category", "title", "body", "link", "resource_kind", "resource_id"], required: ["recipient_kind", "recipient_id", "title"], operations: ["list", "get", "create", "delete"], actions: NOTIFICATION_ACTIONS, fields: ["id", "recipient_kind", "recipient_id", "recipient_tenant_id", "category", "title", "body", "link", "resource_kind", "resource_id", "read_at", "created_at"] },
  { name: "ActionLog", label: "Action Log", module: "platform", id: "action_log_read", table: "platform_action_log", idColumn: "id", defaultSort: "created_at", fields: ["id", "agent_id", "action", "scope", "payload_hash", "result", "created_at"] },
  {
    name: "OperationRun",
    label: "Operation Run",
    module: "platform",
    id: "operation_run_service",
    table: "kernel_operation_runs",
    defaultSort: "updated_at",
    accessPolicy: "tenant-member",
    fields: ["id", "tenant_id", "actor_id", "object_type", "record_id", "action_name", "status", ["progress", "Float"], ["result_json", "JSON"], "error_code", "error_message", "created_at", "updated_at", "finished_at"],
    actions: [
      {
        name: "cancel",
        label: "Cancel",
        target: "record",
        effect: "write",
        execution: "sync",
        roles: ["owner", "intelligence"],
        confirmation: { required: true, ttlSeconds: 120 },
        inputSchema: { type: "object", additionalProperties: false },
      },
    ],
  },
  {
    name: "Release",
    label: "Release",
    module: "platform",
    id: "release_service",
    table: "releases",
    database: "core",
    scope: "admin",
    operations: ["list", "get"],
    actions: RELEASE_ACTIONS,
    fields: ["id", "version", "channel", "published_at", "discovered_at"],
  },
  {
    name: "InstallationUpdateState",
    label: "Installation Update State",
    module: "platform",
    id: "installation_update_state_service",
    table: "installation_update_state",
    database: "core",
    scope: "admin",
    operations: ["list", "get"],
    actions: UPDATE_ACTIONS,
    fields: [
      "id",
      "installation_uuid",
      "current_version",
      "channel",
      ["auto_check", "Check"],
      "status",
      "available_release_id",
      "target_version",
      "release_notes",
      "release_notes_url",
      ["download_size", "Int"],
      "compatibility_status",
      ["update_available", "Check"],
      "installation_surface",
      "backup_status",
      ["can_apply", "Check"],
      "apply_hint",
      "image_digest",
      "downloaded_path",
      "skipped_version",
      "deferred_until",
      "manifest_url",
      "last_checked_at",
      "last_error",
      ["poll_min_ms", "Int"],
      ["poll_max_ms", "Int"],
      "updated_at",
    ],
  },
  {
    name: "User",
    label: "User",
    module: "platform",
    id: "user_admin_service",
    table: "users",
    database: "core",
    scope: "admin",
    writable: ["email", "display_name", "is_admin"],
    required: ["email", "display_name"],
    operations: ["list", "get", "update", "delete"],
    actions: IDENTITY_ADMIN_ACTIONS.User,
    fields: ["id", "email", "display_name", "avatar_url", ["is_admin", "Check"], ["tenant_count", "Int"], "created_at"],
  },
  {
    name: "UserProfile",
    label: "User Profile",
    module: "platform",
    id: "user_profile_service",
    table: "user_profiles",
    database: "core",
    scope: "user",
    writable: ["display_name", "avatar_url", "headline", "bio", "pronouns", "location", "timezone", "phone", "company", "job_title", "website", "twitter", "github", "linkedin", "emoji", "birthday", "languages", "interests", "values", "goals", "personality_notes", "decision_style", "risk_tolerance"],
    operations: ["list", "get", "update"],
    actions: IDENTITY_ADMIN_ACTIONS.UserProfile,
    fields: ["id", "user_id", "email", "display_name", "avatar_url", "headline", "bio", "pronouns", "location", "timezone", "phone", "company", "job_title", "website", "twitter", "github", "linkedin", "emoji", "birthday", "languages", "interests", "values", "goals", "personality_notes", "decision_style", "risk_tolerance", "created_at", "updated_at"],
  },
  {
    name: "UserCredential",
    label: "User Credential",
    module: "platform",
    id: "user_credential_service",
    table: "users",
    database: "core",
    scope: "user",
    operations: ["list", "get"],
    actions: IDENTITY_ADMIN_ACTIONS.UserCredential,
    fields: ["id", "user_id", ["has_password", "Check"], ["has_oauth", "Check"], "updated_at"],
  },
  {
    name: "Tenant",
    label: "Tenant",
    module: "platform",
    id: "tenant_admin_service",
    table: "tenants",
    database: "core",
    scope: "tenant",
    writable: ["name", "slug", "owner_user_id"],
    required: ["name"],
    operations: ["list", "get", "create", "update", "delete"],
    actions: IDENTITY_ADMIN_ACTIONS.Tenant,
    fields: ["id", "name", "slug", ["is_operator", "Check"], "owner_user_id", "created_at", "updated_at"],
  },
  {
    name: "TenantMembership",
    label: "Tenant Membership",
    module: "platform",
    id: "tenant_membership_service",
    table: "tenant_memberships",
    database: "core",
    scope: "tenant",
    writable: ["user_id", "tenant_id", "role"],
    required: ["user_id", "role"],
    operations: ["list", "get", "create", "update", "delete"],
    actions: IDENTITY_ADMIN_ACTIONS.TenantMembership,
    fields: ["id", "user_id", "tenant_id", "role", "created_at"],
  },
  {
    name: "TenantProvisioningRun",
    label: "Tenant Provisioning Run",
    module: "platform",
    id: "tenant_provisioning_run_service",
    table: "platform_meta",
    database: "core",
    scope: "user",
    operations: ["list", "get"],
    fields: ["id", "operation", "status", "actor_user_id", "owner_user_id", "tenant_id", "tenant_name", "tenant_slug", "error", "created_at", "updated_at"],
  },
  {
    name: "PlatformBillingConfig",
    label: "Platform Billing Config",
    module: "platform",
    id: "platform_billing_config_service",
    table: "platform_meta",
    database: "core",
    scope: "admin",
    operations: ["list", "get"],
    actions: PLATFORM_CONFIG_ACTIONS.PlatformBillingConfig,
    fields: ["id", ["configured", "Check"], "publishable_key", ["credits_per_usd", "Float"], ["has_secret_key", "Check"]],
  },
  {
    name: "TenantOnboardingConfig",
    label: "Tenant Onboarding Config",
    module: "platform",
    id: "tenant_onboarding_config_service",
    table: "ai_settings",
    scope: "tenant",
    operations: ["list", "get"],
    actions: PLATFORM_CONFIG_ACTIONS.TenantOnboardingConfig,
    fields: ["id", "tenant_id", ["completed", "Check"], ["llm_ready", "Check"], ["cursor_connected", "Check"], ["llm_status", "JSON"]],
  },
  { name: "ShareGrant", label: "Share Grant", module: "platform", id: "share_grant_read", table: "share_grants", database: "core", scope: "tenant", scopeColumn: "owner_tenant_id", defaultSort: "updated_at", writable: ["resource_kind", "resource_id", "grantee_user_id", "grantee_tenant_id", "role", "expires_at"], required: ["resource_kind", "resource_id"], operations: ["list", "get", "create", "delete"], actions: PLATFORM_ACTION_METADATA.ShareGrant, fields: ["id", "owner_tenant_id", "owner_user_id", "resource_kind", "resource_id", "grantee_user_id", "grantee_tenant_id", "role", "expires_at", "created_at", "updated_at"] },
];
