import type { LucideIcon } from "lucide-react";
import {
  ActivityIcon,
  AlarmClockIcon,
  BarChart3Icon,
  BookOpenIcon,
  BriefcaseIcon,
  Building2Icon,
  CalendarIcon,
  CheckSquareIcon,
  CircleIcon,
  CoinsIcon,
  CompassIcon,
  CpuIcon,
  DatabaseIcon,
  DollarSignIcon,
  FactoryIcon,
  FlagIcon,
  FolderIcon,
  GaugeIcon,
  GlobeIcon,
  HomeIcon,
  HourglassIcon,
  LandmarkIcon,
  LayersIcon,
  LayoutDashboardIcon,
  LineChartIcon,
  ListChecksIcon,
  Megaphone as MegaphoneIcon,
  NotebookPenIcon,
  PackageIcon,
  PieChartIcon,
  RocketIcon,
  Settings2Icon,
  ShieldIcon,
  ShoppingBagIcon,
  StoreIcon,
  TargetIcon,
  TrendingUpIcon,
  TruckIcon,
  UserIcon,
  UsersIcon,
  WrenchIcon,
  ZapIcon,
} from "lucide-react";

const REGISTRY: Record<string, LucideIcon> = {
  activity: ActivityIcon,
  "alarm-clock": AlarmClockIcon,
  "bar-chart-3": BarChart3Icon,
  "book-open": BookOpenIcon,
  briefcase: BriefcaseIcon,
  "building-2": Building2Icon,
  calendar: CalendarIcon,
  "check-square": CheckSquareIcon,
  circle: CircleIcon,
  coins: CoinsIcon,
  compass: CompassIcon,
  cpu: CpuIcon,
  database: DatabaseIcon,
  "dollar-sign": DollarSignIcon,
  factory: FactoryIcon,
  flag: FlagIcon,
  folder: FolderIcon,
  gauge: GaugeIcon,
  globe: GlobeIcon,
  home: HomeIcon,
  hourglass: HourglassIcon,
  landmark: LandmarkIcon,
  layers: LayersIcon,
  "layout-dashboard": LayoutDashboardIcon,
  "line-chart": LineChartIcon,
  "list-checks": ListChecksIcon,
  megaphone: MegaphoneIcon,
  "notebook-pen": NotebookPenIcon,
  package: PackageIcon,
  "pie-chart": PieChartIcon,
  rocket: RocketIcon,
  "settings-2": Settings2Icon,
  shield: ShieldIcon,
  "shopping-bag": ShoppingBagIcon,
  store: StoreIcon,
  target: TargetIcon,
  "trending-up": TrendingUpIcon,
  truck: TruckIcon,
  user: UserIcon,
  users: UsersIcon,
  wrench: WrenchIcon,
  zap: ZapIcon,
};

export const ICON_NAMES: string[] = Object.keys(REGISTRY).sort();

export function iconByName(name: string | undefined | null): LucideIcon {
  if (!name) return CircleIcon;
  return REGISTRY[name] ?? CircleIcon;
}
